version: '3.8'

###### SERVICES ######

services:
  nginx:
    container_name: nginx_container
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx_image:custom
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - /var/www/html
      - /etc/ssl/certs
      - wp_vol:/var/www/html
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wp_container
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wp_image:custom
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception


  mariadb:
    container_name: mariadb_container
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_ROOT_PASS=${DB_ROOT_PASS}
    image: mariadb_image:custom
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception


######## VOLUMES ########

volumes:
  wp_vol:
    driver: local
    driver_opts:
    #This option indicates that the "bind mount" option is being used, which links a directory or file from the host's file system directly to the container.
      o: bind
      #It indicates that a specific type of Docker volume, such as "tmpfs" or "nfs," is not being used.
      type: none
      device : /home/framos-p/data/wordpress
  mariadb_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/framos-p/data/mariadb

######### NETWORK ########

networks:
  inception:
    name: inception
    driver: bridge
